spring:
  datasource:
    url: url to db
    username: username
    password: password
  jackson:
    serialization:
      fail-on-empty-beans: false # https://stackoverflow.com/questions/24994440/no-serializer-found-for-class-org-hibernate-proxy-pojo-javassist-javassist

server:
  port: 8082
  ssl:
    certificate-private-key: ..\ssl\localhost-key.pem
    certificate: ..\ssl\localhost.pem